package com.sandisk.zs.type;

/**
 * File: ZSStatisticsDescribe.java 
 * Author: zane, ymiao, candy
 * 
 * Created on July 30, 2013
 * 
 * SanDisk Proprietary Material, © Copyright 2013 SanDisk, all rights reserved.
 * http://www.sandisk.com THIS IS NOT A CONTRIBUTION
 */

/**
 * Describe the states for zs such as assess, cache, flash state.
 */
public class ZSStatisticsDescribe {
	
	public static enum ZSCacheStat{
		ZS_CACHE_STAT_CACHE_MISSES(15), 
		ZS_CACHE_STAT_CACHE_HITS(16);
		
		private int value;
		private ZSCacheStat(int value){
			this.value = value;
		}
		public int getValue(){
			return value;
		}
	}

	public String[] accessDescArray = new String[]{
			"num_created_objs_with_expiry",
			"num_created_objs",
			"num_put_objs_with_expiry",
			"num_put_objs",
			"num_set_objs_with_expiry",
			"num_set_objs",
			"num_get_objs_and_check_expiry",
			"num_get_objs",
			"num_del_objs_with_expiry",
			"num_del_objs",
			"num_flush_objs",
			"num_flush_and_invalidate_objs",
			"num_invalidate_objs",
			"num_sync_to_flash", 
			"num_delayed_invalidates",
			"delayed_invalidation_time",
			"num_flush_container",
			"num_flush_and_invalidate_container",
			"num_invalidate_container",
			"num_remote_invalidations",
			"num_remote_updates",
			"completed_enumerations",
			"active_enumerations",
			"objects_enumerated",
			"cached_objects_enumerated",
			"num_container_deletes_pending",
			"num_container_deletes_progress",
			"num_reads",
			"num_writes",
			"num_deletes",
			"num_flushes",
			"num_mputs",
			"num_msets",
			"num_range",
			"num_range_next",
			"num_range_finish",
			"num_range_updates",
			"num_create_snapshots",
			"num_delete_snapshots",
			"num_list_snapshots",
			"num_transaction_starts",
			"num_transaction_commits"
	};
	
	public String[] flashStateDescArray = new String[]{
			"num_items_flash",
		    "num_items_created",
		    "num_evictions_flash",
		    "num_hash_evictions",
		    "num_inval_evictions",
		    "num_soft_overflows",
		    "num_hard_overflows",
		    "num_get_hash_collisions",
		    "num_set_hash_collisions",
		    "num_overwrites",
		    "num_flash_ops",
		    "num_read_ops",
		    "num_get_ops",
		    "num_put_ops",
		    "num_del_ops",
		    "num_existence_checks",
		    "num_full_hash_buckets",
		    "num_pending_ios",
		    "flash_space_allocated",
		    "flash_space_consumed",
		    "slab_gc_segments_compacted",
		    "slab_gc_segments_freed",
		    "slab_gc_slabs_relocated",
		    "slab_gc_blocks_relocated",
		    "slab_gc_relocate_errors",
		    "slab_gc_signalled",
		    "slab_gc_signalled_sync",
		    "slab_gc_wait_sync",
		    "slab_gc_segments_cancelled",
		    "slab_free_segments",
		    "flash_compressed_bytes",
		    "zs_thd_contexts"
	};
	
	public String[] cacheStateDescArray = new String[]{
			"num_overwrites_s_state",		  
			"num_overwrites_m_state",
		    "num_inplace_overwrites_s_state",
		    "num_inplace_overwrites_m_state",
		    "num_new_entries",
		    "num_writethrus_to_flash",
		    "num_writebacks",
		    "num_flush_ops_to_flash",
		    "async_drains",
		    "async_puts",
		    "async_put_fails",
		    "async_flushes",
		    "async_flush_fails",
		    "async_wrbks",
		    "async_wrbk_fails",
		    "cache_misses",
		    "cache_hits",
		    /* request from cache to flash manager */
		    "num_create_objs",
		    "num_create_objs_and_put",
		    "num_create_objs_with_data",
		    "num_delete_objs",
		    "num_flush_objs",
		    "num_get_objs_to_read",
		    "num_get_objs_to_write",
		    "num_put_objs",
		    "num_set_objs",
		    "num_set_objs_and_put",
		    /* Request from flash manager to cache */
		    "num_create_objs_completed",
		    "num_create_objs_failed",
		    "num_castout_completed",
		    "num_castout_failed",
		    "num_delete_objs_completed",
		    "num_delete_objs_failed",
		    "num_flush_objs_completed",
		    "num_flush_objs_failed",
		    "num_get_objs_to_read_completed",
		    "num_get_objs_to_read_failed",
		    "num_get_objs_to_write_completed",
		    "num_get_objs_to_write_failed",
		    "num_put_objs_completed",
		    "num_put_objs_failed",
		    "num_set_objs_completed",
		    "num_set_objs_failed",
		    "num_existence_checks",
		    "num_existence_success",
		    "num_existence_failed",
		    "num_get_objs",
		    "num_objs_data",
		    "num_get_objs_failed",
		    "num_put_objs",
		    "num_put_objs_completed",
		    "num_put_objs_failed",
		    "num_delete_objs",
		    "num_delete_completed",
		    "num_delete_failed",
		    "num_create_objects",
		    "num_create_completerdf",
		    "num_create_failed",
		    "num_create_zeroed_objs",
		    "num_create_zeroed_objs_completed",
		    "num_create_zeroed_objs_failed",
		    "num_set_objs",
		    "num_set_objs_completed",
		    "num_set_objs_failed",
		    "num_create_shards",
		    "num_create_shards_completed",
		    "num_create_shards_failed",
		    "num_sync_shards",
		    "num_sync_shards_completed",
		    "num_sync_shards_failed",
		    "num_delete_shards",
		    "num_delete_shards_completed",
		    "num_delete_shards_failed",
		    "num_get_last_seq",
		    "num_get_last_seq_completed",
		    "num_get_last_seq_failed",
		    "num_get_iter_cursors",
		    "num_get_iter_cursors_completed",
		    "num_get_iter_cursors_failed",
		    "num_get_by_cursors",
		    "num_get_by_cursors_completed",
		    "num_get_by_cursors_failed",
		    "num_get_seq_numbers",
		    "num_get_container_stats",
		    "num_get_container_stats_completed",
		    "num_get_container_stats_failed",
		    "num_replication_starts",
		    "num_replication_starts_completed",
		    "num_replication_starts_failed",
		    "num_replication_stops",
		    "num_replication_stops_completed",
		    "num_replication_stops_failed",
		    "num_flush_objs",
		    "num_flush_objs_completed",
		    "num_flush_objs_failed",
		    "num_release_vip_grps",
		    "num_release_vip_grps_completed",
		    "num_release_vip_grps_failed",
		    "num_noop",
		    "num_noop_completed",
		    "num_noop_failed",
		    "num_open_shards",
		    "num_open_shards_completed",
		    "num_open_shards_failed",
		    "num_flush_objs",
		    "num_flush_objs_completed",
		    "num_flush_objs_fialed",
		    "num_flush_invalidate_objs",
		    "num_flush_invalidate_objs_completed",
		    "num_flush_invalidate_objs_failed",
		    "num_invalidate_objs",
		    "num_invalidate_objs",
		    "num_invalidate_objs",
		    "num_flush_containers",
		    "num_flush_containers_completed",
		    "num_flush_containers_failed",
		    "num_flush_invalidate_containers",
		    "num_flush_invalidate_containers_completed",
		    "num_flush_invalidate_containers_failed",
		    "num_invalidate_containers",
		    "num_invalidate_containers_completed",
		    "num_invalidate_containers_failed",
		    "num_success",
		    "num_errors_not_permitted_",
		    "num_errors_objects_not_found",
		    "num_errors_insufficient_buffer",
		    "num_errors_container_stopped",
		    "num_errors_container_not_found",
		    "num_errors_delete_failed",
		    "num_errors_try_again",
		    "num_errors_no_memory",
		    "num_errors_perm_denied",
		    "num_errors_replication_inconsistencies",
		    "num_errors_dev_busy",
		    "num_errors_obj_exists",
		    "num_errors_invalid_arguments",
		    "num_errors_too_many_objs",
		    "num_errors_no_flash_space",
		    "num_errors_no_system_resource",
		    "num_errors_stale_data",
		    "num_errors_quota_exceeded",
		    "num_errors_remote_delete_failures",
		    "num_errors_no_remote_container",
		    "num_hash_buckets_in_cache",
		    "num_cache_partitions",
		    "num_objects_in_cache",
		    "max_cache_capacity",
		    "current_data_size_in_cache",
		    "current_key_and_data_size_in_cache",
		    "num_modified_objs_in_cache",
		    "num_bytes_of_modified_objs_in_cache",
		    "num_mod_objs_flushed",
		    "num_mod_objs_flushed_by_bgflush",
		    "num_pending_remote_cache_req",
		    "num_modified_objs_copied_during_recovery",
		    "background_flush_progress",
		    "num_background_flushes",
		    "max_parallel_flushes",
		    "max_parallel_bg_flushes",
		    "time_to_wait_after_bgflush_for_nodirty_data",
		    "max_percent_limit_on_modifiable_cache",
		    "num_app_buffers_inuse",
		    "num_cache_ops_in_progress",
		    "num_flash_data_buffer_being_processed",
		    "num_resp_msg_being_processed",
	};

    public String[] cntrDescArray = new String[]{
            "num_objs",
            "used_space",
    };
}
